language: go
dist: bionic

go:
  - 1.13.x

before_install:
  - wget -O - -q https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.21.0

script:
  - golangci-lint run
  - go test ./...
