language: go
dist: bionic

go:
  - 1.13.x

before_install:
  - wget -O - -q https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| bash -s -- -b $GOPATH/bin v1.21.0

script:
  - $GOPATH/bin/golangci-lint run
  - go test ./...
